permalink: /:title

# Sidebar ad
sidebarAd:
  - banner: /images/posts/sbw-tattoo-guy-register.jpg
    link: http://SmallBizzWorks.com/blog
    alt: Advertisment

# Site authors
# append to list whenever an author is added
author:
  - name: BHWeb
    avatar:

# ------------------------------------------------------
# Site wide - Do not alter unless you know what you're doing
# ------------------------------------------------------
title: Small Bizz Works
email: brenthack35@gmail.com
contact-email: mailto:brenthack35@gmail.com
description: A local community of small business owners, entrepreneurs and professionals. A place to share ideas and work together to promote small business.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://SmallBizzWorks.com"
forum_url: "http://SmallBizzWorks.com/blog"
logo: /images/SBW-LOGO.png
twitter_username: smallbizzworks
github_username:  SmallBizzWorks
subscribe_url: /feed.xml
copyright: Small Bizz Works. All rights reserved.
address: 440 A W 28th Division Hwy, Lititz, PA 17543

# See into the future
future: true

#google-analytics
tracking-code: UA-99331513-1
google_ad_client: ca-pub-1947952316903944

gems:

# SASS
sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - getruby.cmd
  - README.md

# Social - Ritter social accounts
social_links:
  - service: twitter
    url: https://twitter.com/smallbizzworks
  - service: facebook-official
    url: https://www.facebook.com/Small-Bizz-Works-297967847315539/
